### PR TITLE
chore(eo): bump version 0.38.0 -> 0.38.3

### LINKED ISSUE #397: Bump the `eo` version
New `eo` version was released - https://github.com/objectionary/eo/releases/tag/0.38.3.

### PR DESCRIPTION
**Pull request by deemp**
Closes #397

## TODO

- [ ] don't save all pipeline files to an artifact (introduced in https://github.com/objectionary/normalizer/pull/398/commits/fb8b8faf7eb22da96ec796668381764c8c4309a3)

---

## PR-Codex overview
This PR updates `eolang` to version `0.21.1`, adds `--home-tag=0.38.2` to `eo` function, and modifies various `.phi` files in `eo-phi-normalizer`.

### Detailed summary
- Updated `eolang` to version `0.21.1`
- Added `--home-tag=0.38.2` to `eo` function
- Modified multiple `.phi` files in `eo-phi-normalizer`

> The following files were skipped due to too many changes: `eo-phi-normalizer/data/0.38.3/org/eolang/bytes.phi`, `eo-phi-normalizer/data/0.38.3/org/eolang/tuple.phi`, `eo-phi-normalizer/data/0.38.3/org/eolang/float.phi`, `eo-phi-normalizer/data/0.38.3/org/eolang/positive-infinity.phi`, `eo-phi-normalizer/data/0.38.3/org/eolang/negative-infinity.phi`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by deemp** [comment]
@maxonfjvipon, here's an artifact ([link](https://github.com/objectionary/normalizer/actions/runs/9411899039/artifacts/1577841853)) with files generated during the pipeline run (except some `.eoc` files). The `pipeline` directory structure is described on our site ([link](https://www.objectionary.com/normalizer/docs/pipeline.html#explore-the-pipeline-directory)).

For now, I have no idea how to search for a problematic file that triggers this error. Could you please advise how to search for it? Or, better, could you please improve the error message on your side?

You can use https://github.com/mxschmitt/action-tmate if you need to see what happens on a runner.

**Comment by maxonfjvipon** [comment]
@deemp could you please provide an artifact with all files from `.eoc` directory?

**Comment by deemp** [comment]
@maxonfjvipon, see https://github.com/objectionary/normalizer/actions/runs/9451215173/artifacts/1586079288

**Review by fizruk — APPROVED** [review]

**Comment by deemp** [comment]
Already updated to 0.38.4 in https://github.com/objectionary/normalizer/pull/426

**Pull request closed without merging**
